language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6

script:
    - VERBOSE=true ./tests/run-tests.sh -s tests/
    - php code-checker/src/code-checker.php -i use.latte

services:
    - memcached

before_script:
    # Install Nette Tester & Code Checker
    - travis_retry composer install --no-interaction --prefer-dist
    - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction

    # Create databases.ini
    - cp ./tests/Nette/Database/databases.sample.ini ./tests/Nette/Database/databases.ini

    # Create Postgre database
    - psql -c 'CREATE DATABASE nette_test' -U postgres

git:
    depth: 10

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
